# Generated by Django 4.1.7 on 2023-03-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeparapp", "0004_add_delete_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=250, verbose_name="Адрес")),
                ("price_low", models.CharField(max_length=15, verbose_name="Цена от")),
                ("price_high", models.CharField(max_length=15, verbose_name="Цена до")),
                ("s", models.CharField(max_length=15, verbose_name="s")),
                ("url", models.CharField(max_length=15, verbose_name="url")),
            ],
            options={
                "verbose_name": "INFO",
                "verbose_name_plural": "INFO`s",
            },
        ),
        migrations.DeleteModel(
            name="Add",
        ),
    ]
