# Generated by Django 4.1.7 on 2023-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeparapp", "0005_info_delete_add"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=250, verbose_name="Адрес")),
            ],
        ),
        migrations.CreateModel(
            name="High",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_high", models.CharField(max_length=15, verbose_name="Цена до")),
            ],
        ),
        migrations.CreateModel(
            name="Low",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_low", models.CharField(max_length=15, verbose_name="Цена от")),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=15, verbose_name="s")),
            ],
        ),
        migrations.DeleteModel(
            name="Info",
        ),
    ]
